name: ai-tester
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: coladimeji/ai-tester
  source_dir: /
  http_port: 4000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
    preserve_path_prefix: true
  - path: /